---
  - ORG: sebas-org
    WORKFLOW_NAME: "Semgrep PR workflow"
    WORKFLOW_REPO: "sebas-org/required-workflow"
    WORKFLOW_PATH: "semgrep.yaml"
    PROD: True
    #ADD_REPOS: ["A", "B"]
    #REMOVE_REPOS: []
    AUTHOR_NAME: Sebas Revuelta
    AUTHOR_EMAIL: sebastianrevuelta@gmail.com
    BRANCH: branch-list-updates
    PR_TITLE: Update list of branches
    PR_BODY: |
      Adding new branch to list required workflows
    COMMIT_MESSAGE: Update list of branches in workflow
